/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function overwriteConfig(adminPort: number, keystoreConnectionUrl: string, bootstrapServerUrl: string, signalingServerUrl: string, configPath: string, allowedOrigin: string, iceServerUrls?: Array<string> | undefined | null): string
export function defaultConductorConfig(adminPort: number, keystoreConnectionUrl: string, bootstrapServerUrl: string, signalingServerUrl: string, conductorEnvironmentPath: string, allowedOrigin: string, iceServerUrls?: Array<string> | undefined | null): string
export function decodeHappOrWebhapp(happOrWebhappBytes: Array<number>): Promise<HappAndUiBytes>
export function readAndDecodeHappOrWebhapp(path: string): Promise<HappAndUiBytes>
export function saveWebhapp(path: string, uiTargetDir: string): Promise<string>
export interface KeyFile {
  rootSeed: string
  revocationSeed: string
  deviceSeedsSeed: string
  revocationKey0: string
  deviceSeed0: string
  timestamp: number
}
/**
 * Generates root seed, revocation key and device seed
 *
 * Use a single passphrase for the whole file for starters
 */
export function generateInitialSeeds(passphrase: string): Promise<KeyFile>
export interface ZomeCallUnsignedNapi {
  cellId: Array<Array<number>>
  zomeName: string
  fnName: string
  payload: Array<number>
  capSecret?: Array<number>
  provenance: Array<number>
  nonce: Array<number>
  expiresAt: number
}
export interface ZomeCallNapi {
  cellId: Array<Array<number>>
  zomeName: string
  fnName: string
  payload: Array<number>
  capSecret?: Array<number>
  provenance: Array<number>
  nonce: Array<number>
  expiresAt: number
  signature: Array<number>
}
export interface HappAndUiBytes {
  happBytes: Array<number>
  uiBytes?: Array<number>
}
export type JsLauncherLairClient = LauncherLairClient
export class LauncherLairClient {
  constructor()
  static connect(connectionUrl: string, passphrase: string): Promise<LauncherLairClient>
  signZomeCall(zomeCallUnsignedJs: ZomeCallUnsignedNapi): Promise<ZomeCallNapi>
  seedExists(tag: string): Promise<boolean>
  importLockedSeedBundle(importLockedSeedBundle: string, passphrase: string, tag: string): Promise<string>
  deriveAndImportSeedFromJsonFile(path: string, passphrase?: string | undefined | null): Promise<string>
}
