name: Extract Versions Workflow
on:
  workflow_call:
    outputs:
      version:
        description: "App version"
        value: ${{ jobs.extract-versions.outputs.version }}
      holochain_version:
        description: "Holochain version"
        value: ${{ jobs.extract-versions.outputs.holochain_version }}
      lair_keystore_version:
        description: "Lair keystore version"
        value: ${{ jobs.extract-versions.outputs.lair_keystore_version }}

jobs:
  extract-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Extract version information
        id: packagejson
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "holochain_version=$(node -p "require('./package.json').binaries.holochain")" >> $GITHUB_ENV
          echo "lair_keystore_version=$(node -p "require('./package.json').binaries.lair_keystore")" >> $GITHUB_ENV
    outputs:
      version: ${{ steps.packagejson.outputs.version }}
      holochain_version: ${{ steps.packagejson.outputs.holochain_version }}
      lair_keystore_version: ${{ steps.packagejson.outputs.lair_keystore_version }}