name: 'test-release'
on:
  push:
    branches:
      - feat/binaries-fix

jobs:
  extract-versions:
    uses: ./.github/workflows/get-versions.yaml@main
  create-draft-release:
    needs: extract-versions
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Create Draft Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.extract-versions.outputs.version }}
          name: v${{ needs.extract-versions.outputs.version }} (Holochain v${{ needs.extract-versions.outputs.holochain_version }})
          draft: true
          generateReleaseNotes: true
          allowUpdates: true
  mark-as-prerelease:
    needs: create-draft-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Log versions
        run: |
          echo "Holochain version: ${{ needs.create-draft-release.outputs.holochain_version }}"
          echo "Lair keystore version: ${{ needs.create-draft-release.outputs.lair_keystore_version }}"
      - name: Mark release as pre-release
        run: |
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ needs.create-draft-release.outputs.release_id }} \
            -d '{
              "prerelease": true,
              "draft": false
            }'


