name: 'test-draft-release'
on:
  push:
    branches:
      - feat/gh-action-enhancement

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Get version
        id: packagejson
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.packagejson.outputs.version }}
          name: v${{ steps.packagejson.outputs.version }}
          draft: true
          generateReleaseNotes: true